[platformio]
default_envs = tally

[env:tally]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.3
    Links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^7.2.1

[env:native_test]
platform = native
build_src_filter = -<*>
